name: revision_backend
description: Dart backend for Revision app.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.1.2
  get_it: ^7.2.0

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
  build_runner: ^2.1.11
